-- Insert 100 records with unique descriptions
delete from customer;
INSERT INTO customer (name, description) VALUES ('Customer1', 'Loves hiking and outdoor adventures');
INSERT INTO customer (name, description) VALUES ('Customer2', 'Avid reader of mystery novels');
INSERT INTO customer (name, description) VALUES ('Customer3', 'Enjoys playing the piano');
INSERT INTO customer (name, description) VALUES ('Customer4', 'Passionate about cooking Italian food');
INSERT INTO customer (name, description) VALUES ('Customer5', 'Practices yoga daily');
INSERT INTO customer (name, description) VALUES ('Customer6', 'Tech enthusiast with a love for AI');
INSERT INTO customer (name, description) VALUES ('Customer7', 'Collector of vintage records');
INSERT INTO customer (name, description) VALUES ('Customer8', 'Runs marathons regularly');
INSERT INTO customer (name, description) VALUES ('Customer9', 'Skilled in graphic design');
INSERT INTO customer (name, description) VALUES ('Customer10', 'Plays the violin in a local orchestra');
INSERT INTO customer (name, description) VALUES ('Customer11', 'Enjoys painting landscapes');
INSERT INTO customer (name, description) VALUES ('Customer12', 'Volunteers at animal shelters');
INSERT INTO customer (name, description) VALUES ('Customer13', 'Gardens in their free time');
INSERT INTO customer (name, description) VALUES ('Customer14', 'Enthusiastic about astrophotography');
INSERT INTO customer (name, description) VALUES ('Customer15', 'Practices meditation');
INSERT INTO customer (name, description) VALUES ('Customer16', 'Writes poetry');
INSERT INTO customer (name, description) VALUES ('Customer17', 'Plays chess competitively');
INSERT INTO customer (name, description) VALUES ('Customer18', 'Enjoys scuba diving');
INSERT INTO customer (name, description) VALUES ('Customer19', 'Loves baking desserts');
INSERT INTO customer (name, description) VALUES ('Customer20', 'Practices martial arts');
INSERT INTO customer (name, description) VALUES ('Customer21', 'Fluent in four languages');
INSERT INTO customer (name, description) VALUES ('Customer22', 'Photographs wildlife');
INSERT INTO customer (name, description) VALUES ('Customer23', 'Runs a travel blog');
INSERT INTO customer (name, description) VALUES ('Customer24', 'Enjoys woodworking projects');
INSERT INTO customer (name, description) VALUES ('Customer25', 'Brews their own beer');
INSERT INTO customer (name, description) VALUES ('Customer26', 'Enjoys stargazing');
INSERT INTO customer (name, description) VALUES ('Customer27', 'Writes and directs short films');
INSERT INTO customer (name, description) VALUES ('Customer28', 'Practices calligraphy');
INSERT INTO customer (name, description) VALUES ('Customer29', 'Loves bird watching');
INSERT INTO customer (name, description) VALUES ('Customer30', 'Hosts a podcast on technology');
INSERT INTO customer (name, description) VALUES ('Customer31', 'Passionate about environmental conservation');
INSERT INTO customer (name, description) VALUES ('Customer32', 'Enjoys playing tennis');
INSERT INTO customer (name, description) VALUES ('Customer33', 'Collector of comic books');
INSERT INTO customer (name, description) VALUES ('Customer34', 'Enjoys sailing');
INSERT INTO customer (name, description) VALUES ('Customer35', 'Writes children’s books');
INSERT INTO customer (name, description) VALUES ('Customer36', 'Practices rock climbing');
INSERT INTO customer (name, description) VALUES ('Customer37', 'Enjoys playing the guitar');
INSERT INTO customer (name, description) VALUES ('Customer38', 'Runs a YouTube channel on DIY projects');
INSERT INTO customer (name, description) VALUES ('Customer39', 'Passionate about dance');
INSERT INTO customer (name, description) VALUES ('Customer40', 'Enjoys solving puzzles');
INSERT INTO customer (name, description) VALUES ('Customer41', 'Loves skiing');
INSERT INTO customer (name, description) VALUES ('Customer42', 'Enjoys pottery making');
INSERT INTO customer (name, description) VALUES ('Customer43', 'Runs a small handmade jewelry business');
INSERT INTO customer (name, description) VALUES ('Customer44', 'Enjoys playing the drums');
INSERT INTO customer (name, description) VALUES ('Customer45', 'Passionate about fitness and bodybuilding');
INSERT INTO customer (name, description) VALUES ('Customer46', 'Enjoys reading science fiction novels');
INSERT INTO customer (name, description) VALUES ('Customer47', 'Brews specialty coffee at home');
INSERT INTO customer (name, description) VALUES ('Customer48', 'Loves fishing');
INSERT INTO customer (name, description) VALUES ('Customer49', 'Passionate about car restoration');
INSERT INTO customer (name, description) VALUES ('Customer50', 'Enjoys theater and acting');
INSERT INTO customer (name, description) VALUES ('Customer51', 'Practices archery');
INSERT INTO customer (name, description) VALUES ('Customer52', 'Enjoys exploring caves');
INSERT INTO customer (name, description) VALUES ('Customer53', 'Runs a blog on personal finance');
INSERT INTO customer (name, description) VALUES ('Customer54', 'Loves gourmet cooking');
INSERT INTO customer (name, description) VALUES ('Customer55', 'Enjoys metal detecting');
INSERT INTO customer (name, description) VALUES ('Customer56', 'Plays badminton competitively');
INSERT INTO customer (name, description) VALUES ('Customer57', 'Loves stand-up comedy');
INSERT INTO customer (name, description) VALUES ('Customer58', 'Enjoys amateur astronomy');
INSERT INTO customer (name, description) VALUES ('Customer59', 'Writes a blog about minimalism');
INSERT INTO customer (name, description) VALUES ('Customer60', 'Passionate about cryptocurrency');
INSERT INTO customer (name, description) VALUES ('Customer61', 'Enjoys knitting and crocheting');
INSERT INTO customer (name, description) VALUES ('Customer62', 'Loves gardening and growing vegetables');
INSERT INTO customer (name, description) VALUES ('Customer63', 'Runs a home-based bakery');
INSERT INTO customer (name, description) VALUES ('Customer64', 'Enjoys digital painting');
INSERT INTO customer (name, description) VALUES ('Customer65', 'Loves brewing kombucha');
INSERT INTO customer (name, description) VALUES ('Customer66', 'Enjoys leather crafting');
INSERT INTO customer (name, description) VALUES ('Customer67', 'Passionate about mountaineering');
INSERT INTO customer (name, description) VALUES ('Customer68', 'Loves attending music festivals');
INSERT INTO customer (name, description) VALUES ('Customer69', 'Practices judo');
INSERT INTO customer (name, description) VALUES ('Customer70', 'Enjoys hiking and exploring nature');
INSERT INTO customer (name, description) VALUES ('Customer71', 'Writes historical fiction');
INSERT INTO customer (name, description) VALUES ('Customer72', 'Passionate about sustainable living');
INSERT INTO customer (name, description) VALUES ('Customer73', 'Enjoys carpentry and furniture making');
INSERT INTO customer (name, description) VALUES ('Customer74', 'Loves kite surfing');
INSERT INTO customer (name, description) VALUES ('Customer75', 'Runs a local theater group');
INSERT INTO customer (name, description) VALUES ('Customer76', 'Enjoys bonsai gardening');
INSERT INTO customer (name, description) VALUES ('Customer77', 'Loves roller skating');
INSERT INTO customer (name, description) VALUES ('Customer78', 'Practices flamenco dance');
INSERT INTO customer (name, description) VALUES ('Customer79', 'Enjoys writing software tutorials');
INSERT INTO customer (name, description) VALUES ('Customer80', 'Passionate about classical music');
INSERT INTO customer (name, description) VALUES ('Customer81', 'Loves surfing');
INSERT INTO customer (name, description) VALUES ('Customer82', 'Runs a book club');
INSERT INTO customer (name, description) VALUES ('Customer83', 'Enjoys restoring old furniture');
INSERT INTO customer (name, description) VALUES ('Customer84', 'Practices parkour');
INSERT INTO customer (name, description) VALUES ('Customer85', 'Writes reviews for indie games');
INSERT INTO customer (name, description) VALUES ('Customer86', 'Passionate about space exploration');
INSERT INTO customer (name, description) VALUES ('Customer87', 'Loves playing board games');
INSERT INTO customer (name, description) VALUES ('Customer88', 'Enjoys traveling to historical sites');
INSERT INTO customer (name, description) VALUES ('Customer89', 'Runs a nonprofit organization');
INSERT INTO customer (name, description) VALUES ('Customer90', 'Loves making ceramics');
INSERT INTO customer (name, description) VALUES ('Customer91', 'Passionate about vegan cooking');
INSERT INTO customer (name, description) VALUES ('Customer92', 'Enjoys learning new languages');
INSERT INTO customer (name, description) VALUES ('Customer93', 'Loves participating in hackathons');
INSERT INTO customer (name, description) VALUES ('Customer94', 'Enjoys playing soccer');
INSERT INTO customer (name, description) VALUES ('Customer95', 'Runs a fitness vlog');
INSERT INTO customer (name, description) VALUES ('Customer96', 'Enjoys painting miniatures');
INSERT INTO customer (name, description) VALUES ('Customer97', 'Loves practicing photography');
INSERT INTO customer (name, description) VALUES ('Customer98', 'Writes about film criticism');
INSERT INTO customer (name, description) VALUES ('Customer99', 'Passionate about jazz music');
INSERT INTO customer (name, description) VALUES ('Customer100', 'Enjoys practicing mindfulness meditation');